### ISSUE TITLE
Using Kubernetes version: v1.6.6 failing

### ISSUE THREAD

**Issue by anandkolli** [Intel-Corp/multus-cni#11]
Hello,

I facing an issue with multus running on 1.6.6 kubernetes version.
Jun 22 17:07:24 wn1-virtual-machine kubelet[22909]: E0622 17:07:24.880168   22909 remote_runtime.go:109] StopPodSandbox "c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-dns-692378583-pvrv9_kube-system" network: **Multus: Err in  reading the delegates: failed to read container data in the** path("/var/lib/cni/multus/c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f"): open /var/lib/cni/multus/c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f: no such file or directory
"Jun 22 17:07:24 wn1-virtual-machine kubelet[22909]: E0622 17:07:24.880543   22909 kuberuntime_gc.go:138] Failed to stop sandbox "c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f" before removing: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-dns-692378583-pvrv9_kube-system" network: Multus: Err in  reading the delegates: failed to read container data in the path("/var/lib/cni/multus/c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f"): open /var/lib/cni/multus/c9e530e16dfc884a9d555e2d4bf96c06a3895959ba748b65c0d7cb407da85e4f: no such file or directory"

Below are the steps that I followed:
1) kubeadm init
2) copied multus to /opt/cni/bin
3)root@wn1-virtual-machine:/etc/cni/net.d# kubectl get pods --all-namespaces --show-all  | grep dns
kube-system   kube-dns-692378583-pvrv9                      0/3       ContainerCreating   0          47m

4) files used as suggested in issue for 1.6.4
5) root@wn1-virtual-machine:/etc/cni/net.d# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:00:fb:39 brd ff:ff:ff:ff:ff:ff
    inet 192.168.63.192/24 brd 192.168.63.255 scope global dynamic ens33
       valid_lft 1129sec preferred_lft 1129sec
    inet6 fe80::ca84:383e:dd8c:2181/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ae:37:4a:d4 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default
    link/ether 2a:64:3f:43:70:c4 brd ff:ff:ff:ff:ff:ff

6) root@wn1-virtual-machine:/etc/cni/net.d# cat 10-multus.conf
{
  "name": "multus-demo",
  "type": "multus",
  "delegates": [
    {
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.122.0/24",
        "rangeStart": "192.168.122.200",
        "rangeEnd": "192.168.122.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.122.1"
     }
    },
    {
      "type": "flannel",
      "masterplugin": true,
      "delegate": {
        "isDefaultGateway": true
      }
    }
  ]
}

7) root@wn1-virtual-machine:~# cat flannel-rbac.yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system

8) root@wn1-virtual-machine:~# cat multus.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-multus-cfg
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "multus-demo",
      "type": "multus",
      "delegates": [
        {
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.122.0/24",
            "rangeStart": "192.168.122.200",
            "rangeEnd": "192.168.122.216",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "192.168.122.1"
         }
        },
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            "isDefaultGateway": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
spec:
  template:
    metadata:
      labels:
        tier: node
        app: multus
    spec:
      hostNetwork: true
      # nodeSelector:
      #  beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: flannel
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.7.0-amd64
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel:v0.7.0-amd64
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-multus.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-multus-cfg

Please help me out in resolving this issue.

Thank you.

**Comment by rkamudhan** [comment]
Hi @anandkolli  can you see the solution provided in  #9

**Comment by rkamudhan** [comment]
@anandkolli Can I close this issue ?

**Comment by anandkolli** [comment]
Yes, Please close the issue.

Thanks,
Anand
