### ISSUE TITLE
Cleaning up the reserved IPAM, in case of plugin failure in Multus CNI.

### ISSUE THREAD

**Issue by rkamudhan** [Intel-Corp/multus-cni#2]
If there's malformed configuration in the 'delegates' table in the Multus configuration file and at least one Flannel plugin instance is working correctly, Multus will keep creating interfaces and reserving consecutive IP addresses from the subnet range specified in the Flannel configuration. This will eventually lead to the preservation of entire range from specified subnet and will block the creation of any new K8s pods with Flannel interface.
Moreover, we haven't found any recovery actions after failure, that would do automatic cleanup by itself. We had to remove leftovers after failed pod creation attempts manually by removing failed files and directories from /var/lib/cni/networks/ directory.
Noteworthy 'restartPolicy' option in the pod configuration was set to 'Never'.
Steps to reproduce:
1) Create Multus configuration file containing at least one properly configured Flannel entry and at least one malformed entry. Example:
```
cat /etc/cni/net.d/multus-cni.conf
{
    "name": "minion1-multus-demo-network",
    "type": "multus",
    "delegates": [
        {
                "type": "flannel",
                "masterplugin": true,
                "delegate": {
                        "isDefaultGateway": true
                }
        },
        {
                "type": "foobar"
        }
    ]
}
```
2) Restart kubelet service.
3) Create new pod.

**Comment by plwhite** [comment]
This may be naive (I have not looked at the code, just from use of it in testing), but my understanding is that multus with two networks, A and B, would create an interface by calling CNI plugin A then B. On a failure of B, could multus not simply call A to delete the provisioned address?

Note that I'm seeing this issue too, but it's not blocking my testing in the short term.

**Comment by rkamudhan** [comment]
Yes, you are correct, I will give the solution by next week for this.

**Comment by rkamudhan** [comment]
@plwhite please check the bug fix #4. In the case of failure in any one of the minion plugins, Multus CNI will clear all the network resources allocated by the previous plugins.

**Comment by plwhite** [comment]
I won't pretend to have done a comprehensive test, but I have tested and it appears to fix the issue. My test case was just to have fouled up my SR-IOV installation so that no interfaces were available, which in the past would lead to flannel cycling blowing up and using all IPs in the flannel network in rapid succession. That error case no longer occurs.

Thanks for the quick turnaround on this one!

**Comment by rkamudhan** [comment]
Thanks @plwhite. I will close the issue

**Comment by rkamudhan** [comment]
@plwhite We created a pull request in cni community https://github.com/containernetworking/cni/pull/379 to add mutlus CNI as the 3rd party plugin. As a Multus CNI user welcome your feed back there.
