### ISSUE TITLE
Multiple interfaces for specific Pod on kubernetes

### ISSUE THREAD

**Issue by John-Lin** [Intel-Corp/multus-cni#26]
Hi folks, 
 AFAIK, multus can give more than one network interface to one container/pod on kubernetes. But in my use case on kubernetes cluster. I only need to give specific pod multiple interfaces. My question is there a method to support the feature that can add specific pod multiple interfaces?

**Comment by ahalim-intel** [comment]
@John-Lin let me get your use case right. So, you want to spin up some pods with multiple interfaces and some pod with a default interface with multus?

**Comment by John-Lin** [comment]
@ahalim-intel exactly. My use case is give some pods multiple interfaces and some pods with default interface.

**Comment by dougbtv** [comment]
I believe you can use the CRD functionality to achieve this, e.g. by
putting in the specs the pods that you want to have multiple interfaces.

**Comment by ahalim-intel** [comment]
@John-Lin This is already supported by multus, please refer to the https://github.com/Intel-Corp/multus-cni/blob/master/README.md 
You can create multiple network objects for your cluster as @dougbtv pointed out. Then in your pod specs you specify how many interface and which network you want for that pod.

**Comment by John-Lin** [comment]
@ahalim-intel @dougbtv  thanks for your quick reply. It works like a charm! I tried the CRD and Multus with my [ovs-cni ](https://github.com/John-Lin/ovs-cni) project that could add multiple interfaces on specific pod. Awesome!
