### ISSUE TITLE
Example CNI Config: Master plugin POD/Service Network, Second Plugin Internet Connectivity

### ISSUE THREAD

**Issue by davidjbrady** [Intel-Corp/multus-cni#28]
Is anyone able to provide an example cni configuration whereby a master plugin. e.g calico provides pod and service connectivity.

And a second plugin only provides NAT'd internet connectivity? This use case will allow eaiser monitoring of internet egress for chargeback purposes.

    {
      "name": "multus-networks",
      "type": "multus",
      "delegates": [
        {
          "cniVersion": "0.1.0",
          "name": "internet",
          "type": "bridge",
	  ?????,
          }
        },
        {
          "name": "k8s-pod-network",
          "cniVersion": "0.1.0",
          "type": "calico",
          "masterplugin": true,
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 1500,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s",
              "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        }
      ]
    }

**Comment by rkamudhan** [comment]
@davidjbrady You getting any error in running the above configuration? you can run any reference and 3rd party plugin with Multus. It supports all.

**Comment by davidjbrady** [comment]
Thanks for responding @rkamudhan 

I'm not receiving any errors with a config like the above example. What I am seeing however is the default route will always be on the masterplugin interface which makes sense.

But what if you want the second interface to be used for Internet Connectivity and the masterplugin interface to just be used for pod networking.

I suspect this is possible with Multus but my attempts havent quite worked out yet... So I'm hoping someone can provide an example configuration that I can experiment with :)

Kind regards

**Comment by rkamudhan** [comment]
@davidjbrady 

Try it - eth0 must be the default gateway interface for your node, Please take care of routes for ipam by refering -  https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local 

```
{
      "name": "multus-networks",
      "type": "multus",
      "delegates": [
        {
	"type": "bridge",
	"bridge": "eth0",
	"isDefaultGateway": true,
	"forceAddress": false,
	"ipMasq": true,
	"hairpinMode": true,
	"ipam": {
		"type": "host-local",
		"subnet": "10.10.0.0/16"
	}
      },
        {
          "name": "k8s-pod-network",
          "cniVersion": "0.1.0",
          "type": "calico",
          "masterplugin": true,
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 1500,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s",
              "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        }
      ]
    }
```

**Comment by davidjbrady** [comment]
Thank you for your help @rkamudhan 

Unfortunately I wasn't able to get this config to work but I kept experimenting and found the ptp plugin to work when all Internet CIDR's are added to the plugins routes. For anyone who's interested please see the below working example.

    {
      "name": "multus-networks",
      "type": "multus",
      "delegates": [
        {
          "cniVersion":"0.1.0",
          "name":"internet",
          "type": "ptp",
          "ipMasq": true,
          "ipam":{
            "type":"host-local",
            "subnet":"192.168.255.0/24",
            "routes":[
              {
                "dst":"2.0.0.0/7"
              },
              ...
            ]
          }
        },
        {
          "name": "k8s-pod-network",
          "cniVersion": "0.1.0",
          "type": "calico",
          "masterplugin": true,
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 1500,
          "ipam": {
              "type": "host-local",
              "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s",
              "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        }
      ]
    }
