### ISSUE TITLE
how to create multiple k8s services with endpoints pointing to different network interfaces

### ISSUE THREAD

**Issue by johnkjacob** [Intel-Corp/multus-cni#35]
I was able to create multiple interfaces (2 flannel overlay networks) with multus for a k8s pod, but the kube service is having endpoints pointing to the default gateway. I would like to have seperate k8s service for the 2 network interface. ie control service ->endpoints with flannel 1 ips:port, data service ->endpoints with flannel 2 ips:ports. Any idea how to achieve this?

**Comment by rkamudhan** [comment]
Will update on this.
