### ISSUE TITLE
cmdAdd results provide results for last delegate

### ISSUE THREAD

**Issue by egernst** [Intel-Corp/multus-cni#36]
As far as I can tell, the returned "result" field for cmdAdd is the result from the last delegate which was added.  I wonder if it'd make sense to embed the other results as well in this reply.  Callers who know to look for these fields would be able to observe the network details for each CNI plugin individually.  Callers who don't know to look for these fields, assuming golfing JSON unmarshaling is used, would not be impacted.

Similar idea to what @mcastelino was suggesting at https://github.com/intel/vhost-user-net-plugin/issues/2

What do you think?

**Comment by rkamudhan** [comment]
Let have an internal discussion on this.
