### ISSUE TITLE
ipvlan config question - master and gateway parameters

### ISSUE THREAD

**Issue by rc979** [Intel-Corp/multus-cni#38]
Hi @rkamudhan 
On [this response from earlier this year ](https://github.com/Intel-Corp/multus-cni/issues/3#issuecomment-281423711) you showed a sample ipvlan configuration for Multus and it seems that you omitted the "master" parameter (which denotes the name of the host interface to enslave as per the IPVLAN CNI plugin), can you please explain why?
I also see that you specified a gateway but, according to the ipvlan driver documents, gateways are not used on ipvlan configurations, would you be able to explain the reasoning behind this? I am assuming this has to do with the IPAM configuration but it's not really clear to me how it fits together.
Thanks.

**Comment by rkamudhan** [comment]
@rc979 Thanks for spotting the error. I changed it. I included the gateway by mistake
