### ISSUE TITLE
Links in README.md

### ISSUE THREAD

**Issue by jellonek** [Intel-Corp/multus-cni#39]
Bond CNI link in main README.md points to rkamudhan's fork of sr-iov plugin instead of https://github.com/Intel-Corp/bond-cni

*edited* later part was based on wrong assumption that intel's fork of sr-iov is stale project

**Comment by rkamudhan** [comment]
@jellonek Updated the readme file :sweat:. Thanks for spotting the error

**Comment by rkamudhan** [comment]
Closing the issue.
