### ISSUE TITLE
Multus not aligned to CNI spec v0.3.0

### ISSUE THREAD

**Issue by nikolas-hermanns** [Intel-Corp/multus-cni#43]
When using calico with spec v0.3.0 (plugin chaining included) with multus I get the following error:

1235 pod_workers.go:186] Error syncing pod af00ed7b-0a97-11e8-bf2f-525400f0a9f1 ("simplesvc-54f8df5889-lhqwl_default(af00ed7b-0a97-11e8-bf2f-525400f0a9f1)"), skipping: failed to "CreatePodSandbox" for "simplesvc-54f8df5889-lhqwl_default(af00ed7b-0a97-11e8-bf2f-525400f0a9f1)" with CreatePodSandboxError: "CreatePodSandbox for pod \"simplesvc-54f8df5889-lhqwl_default(af00ed7b-0a97-11e8-bf2f-525400f0a9f1)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"simplesvc-54f8df5889-lhqwl_default\" network: Multus: Err in delegate conf: delegate must have the field 'type'"

I am using the following multus conf:
{
  "name": "multus-multi-network",
  "type": "multus",
  "policy": {
    "type": "k8s",
    "k8s_api_root": "https://10.96.0.1:443",
    "k8s_auth_token": 
  },
  "kubeconfig": "/etc/cni/net.d/multus-kubeconfig",
  "delegates": [
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "etcd_endpoints": "https://10.10.6.11:2379,https://10.10.6.12:2379",
          "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
          "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
          "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
          "log_level": "info",
          "ipam": {
            "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s",
            "k8s_api_root": "https://10.96.0.1:443",
            "k8s_auth_token": 
          },
          "kubernetes": {
            "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        }
      ],
      "masterplugin": true
    }
  ]
}

**Comment by ahalim-intel** [comment]
@nikolas-hermanns The delegate object in your conf file is missing the required "type" parameters as shown in the error log. "type" refers to the cni plugin executable for that delegate. Please check the Multus README.md  for example configuration.

**Comment by nikolas-hermanns** [comment]
@ahalim-intel Thanks for the answer. In the former spec of CNI that was the case. But now the type of the network went to plugins: [ { "type": calico
We want to make use of this plugin architecture of CNI, since through that more then one plugin can be defined for an interface.
Of course not following the new spec CNI we are able to run multus. But then our Multus and non-Multus deployment have different behaviors.

**Comment by ahalim-intel** [comment]
@nikolas-hermanns Not quite clear what you are saying there. Any parameters a CNI plugin accepts that should still be valid and acceptable when you are using that with Multus. Only requirements here for Multus is that plugin executable are given in "delegates": [] list. So, each objects in the delegates must have a "type": for multus to execute that binary along with other required and supported parameters of that plugin. Multus is agnostic of what and how that plugin handles its own configurations. 

If I understand your use-case correct from the given configuration above, I'd configure multus as below:

```
{
	"name": "multus-multi-network",
	"type": "multus",
	"kubeconfig": "/etc/cni/net.d/multus-kubeconfig",
	"delegates": [{
			"name": "pod-network-1",
			"type": "calico",
			"masterplugin": true,
			"etcd_endpoints": "https://10.10.6.11:2379,https://10.10.6.12:2379",
			"etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
			"etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
			"etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
			"log_level": "info",
			"ipam": {
				"type": "calico-ipam"
			},
			"policy": {
				"type": "k8s",
				"k8s_api_root": "https://10.96.0.1:443",
				"k8s_auth_token": ""
			},
			"kubernetes": {
				"kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
			},
			"plugins": [{
				"type": "<< Other plugins executables that Calico will invoke; e.g., portmap >>"
			}]
		},
		{
			"name": "pod-network-2",
			"type": "<< CNI plugin executable that Multus will invoke >>"
		}
	]
}
```

Please refer to the Multus README.md for reference.

**Comment by nikolas-hermanns** [comment]
Hey, I revisited this and came to the conclusion that when I just add the keys to the config then it is working. Still strange since calicio wants to have the etcd_endpoints etc now inside the plugins dict. However is seems to work.

Thanks for your answers!
