### ISSUE TITLE
Issue with POD redeployment.

### ISSUE THREAD

**Issue by subrnath** [Intel-Corp/multus-cni#48]
I am using this to have ipvlan based networking for the containers. There is a issue found if a Kubernetes POD is terminated and redeployed with the same network K8S object, networking doesn't seem to work fine. We are defined CRT to have network object where plugin type defined as ipvlan. Also in the arguments IPAM defines the subnet CIDR. start and end IP. I have tried following sequences but none of them works to restore it apart from reboot of the node.

1. Delete the K8s Network object files and recreate it before the POD is deployed again,
2. Restart of kubelet.

Problem seems to be with IPV6.

**Comment by dougbtv** [comment]
@subrnath -- since this is apparently an IPAM issue, is this directly related to #54 -- that is -- can we close out this issue as it's being handled elsewhere? 

Thanks!

**Comment by subrnath** [comment]
Probably Yes. we can track it over there. I am closing this thread.
