### ISSUE TITLE
multus on 1.6.4 kubernetes failing

### ISSUE THREAD

**Issue by sbezverk** [Intel-Corp/multus-cni#9]
Hello,

I am trying to use multus on  my all in one test bed, further plan is to add sriov support, but now I have only flannel. I had to deal with some rbac issues, now it is resolved. Still kube dns pod is not starting as it does not see networking running, I suspect kubelet does not see valid networking and does not untain the worker. Here is my config:
I used one of example from previous issue:

apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system

kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-multus-cfg
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "multus",
      "type": "multus",
      "delegates": [
        {
          "type": "macvlan",
          "master": "provider_b0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.10.0/24",
            "rangeStart": "192.168.10.154",
            "rangeEnd": "192.168.10.254",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "192.168.10.1"
         }
        },
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            "isDefaultGateway": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.57.128.0/19",
      "Backend": {
        "Type": "vxlan"
      }
    }

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
spec:
  template:
    metadata:
      labels:
        tier: node
        app: multus
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: multus
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.7.1-amd64
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel:v0.7.1-amd64
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-multus.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-multus-cfg

Appreciate your help
Serguei

**Comment by dougbtv** [comment]
@sbezverk -- can you tell us what a `kubectl describe pod some-pod-name` looks like when you go to create something?

I'm trying to replicate in the meanwhile. I haven't yet tried with Kubernetes 1.6.x, but, I'm spinning up an environment to give it a go. Possibly also running into RBAC issues with Flannel, so I'm going to work through that -- multus in theory shouldn't need any RBAC since (last I knew) it didn't need to call the kube api.

**Comment by dougbtv** [comment]
Alright, I've got a working config for multus under 1.6.4 (assuming, all of 1.6)

https://gist.github.com/dougbtv/c29393ae39b08a9cdf5e582aada0e25e

I also found that after much mucking around to fix the RBAC I had wrong in my own reference configurations, that kube-dns pod was not properliy starting. However, I went ahead and found that pod with:

```
[centos@kube-mult-master ~]$ kubectl get pods --all-namespaces --show-all | grep -i kube-dns
```

And then deleted it with: 

```
kubectl delete pod kube-dns-XXXXYYYY-ZZZZZ
```

It restarted and came back up without issue.

**Comment by sbezverk** [comment]
@dougbtv I had RBAC figured out as flannel was unable to contact subnet manager. now it seems kubelet does not untain the node for kube-dns to start.
`kubectl describe pod kube-dns-1080222536-ddzmf  -n kube-system
Name:           kube-dns-1080222536-ddzmf
Namespace:      kube-system
Node:           /
Labels:         k8s-app=kube-dns
                pod-template-hash=1080222536
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kube-dns-1080222536","uid":"11ed0c93-5038-11e7-87c5-58ac785c...
                scheduler.alpha.kubernetes.io/critical-pod=
Status:         Pending
IP:
Controllers:    ReplicaSet/kube-dns-1080222536
Containers:
  kubedns:
    Image:      gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
    Ports:      10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=sbezverk.cisco.com.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    Limits:
      memory:   170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-m8xnr (ro)
  dnsmasq:
    Image:      gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
    Ports:      53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/sbezverk.cisco.com/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    Requests:
      cpu:              150m
      memory:           20Mi
    Liveness:           http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:        <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-m8xnr (ro)
  sidecar:
    Image:      gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
    Port:       10054/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.sbezverk.cisco.com,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.sbezverk.cisco.com,5,A
    Requests:
      cpu:              10m
      memory:           20Mi
    Liveness:           http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-m8xnr (ro)
Conditions:
  Type          Status
  PodScheduled  False 
Volumes:
  kube-dns-config:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       kube-dns
    Optional:   true
  kube-dns-token-m8xnr:
    Type:       Secret (a volume populated by a Secret)
    SecretName: kube-dns-token-m8xnr
    Optional:   false
QoS Class:      Burstable
Node-Selectors: <none>
Tolerations:    CriticalAddonsOnly=:Exists
                node-role.kubernetes.io/master=:NoSchedule
                node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
                node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  11m           19s             42      default-scheduler                       Warning         FailedScheduling        no nodes available to schedule pods`

**Comment by sbezverk** [comment]
Ok, with some extra tweaks I got going base config, thanks a lot @dougbtv  for your help. Now, on to SRIOV part :)

**Comment by dougbtv** [comment]
No prob! Glad I could be of some help. Mind posting your final working
config and RBAC for posterity / reference in the future? Could be helpful
to others in the future.

Good luck with SR-IOV!

**Comment by sbezverk** [comment]
@dougbtv here is my final version of rbac rules and I also changed service account in yaml to be multus.
```programming
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
```

wrt sriov, I already see some issues and filed new issue, please check it out and comment if you have any suggestions.

**Comment by rkamudhan** [comment]
@dougbtv @sbezverk I will close this case now.. Hope Multus is working in your env.
